In [1]:
import os

In [2]:
os.makedirs(os.path.join('..','data'),exist_ok=True)
data_file=os.path.join('..','data','house_tiny.csv')
with open(data_file,'w') as f:
    f.write('NumRooms,Alley,Price\n')
    f.write('NA,Pave,127500\n')
    f.write('2,NA,106000\n')
    f.write('4,NA,130000\n')
    f.write('NA,NA,140000\n')

In [3]:
import pandas as pd

In [4]:
data=pd.read_csv(data_file)
data

   NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  130000
3       NaN   NaN  140000

In [18]:
inputs=data.iloc[:,0:2]

In [19]:
inputs.iloc[:, 0] = inputs.iloc[:, 0].fillna(inputs.iloc[:, 0].mean())

In [20]:
inputs

   NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN

In [22]:
inputs=pd.get_dummies(inputs,dummy_na=True)
inputs

   NumRooms  Alley_Pave  Alley_nan
0       3.0        True      False
1       2.0       False       True
2       4.0       False       True
3       3.0       False       True

In [23]:
import torch

In [27]:
inputs=inputs.astype(float)

In [28]:
X=torch.tensor(inputs.values)

In [29]:
X

tensor([[3., 1., 0.],
        [2., 0., 1.],
        [4., 0., 1.],
        [3., 0., 1.]], dtype=torch.float64)

练习1 删除缺失值最多的列

In [36]:
def clean_missing_most(df):
    missing_counts = df.isnull().sum()
    missing_counts_max=missing_counts.max()
    missing_counts_max_col=missing_counts[missing_counts==missing_counts_max].index.tolist()
    if missing_counts_max_col:
        col_to_remove = missing_counts_max_col[0]
        return df.drop(columns=[col_to_remove])
    else:
        return df

In [37]:
data=clean_missing_most(data)
data

   NumRooms   Price
0       NaN  127500
1       2.0  106000
2       4.0  130000
3       NaN  140000